controllers/UserController.php
<?php

/**
 */
class UserController extends Controller
{
    public function actionList()
    {
        $group_id = isset($_REQUEST['group_id']) ? $_REQUEST['group_id'] : false;
        $listGroup = PublicModel::getActiveByAdminId($this->admin->id);
        if (!$group_id && count($listGroup)) {
            $group_id = array_keys($listGroup)[0];
        }

        $this->render('user/list', [
            'listUser' => UserModel::getAllWithScores($group_id),
            'listGroup' => $listGroup,
        ]);
    }

    public function actionTop()
    {
        $group_id = isset($_REQUEST['group_id']) ? $_REQUEST['group_id'] : false;
        $listGroup = PublicModel::getActiveByAdminId($this->admin->id);
        if (!$group_id && count($listGroup)) {
            $group_id = array_keys($listGroup)[0];
        }

        $this->render('user/list', [
            'listUser' => TopModel::getLast($group_id, 12),
            'listGroup' => $listGroup,
        ]);
    }

    public function actionGive()
    {
        $scores = isset($_REQUEST['scores']) ? $_REQUEST['scores'] : false;
        $user_id = isset($_REQUEST['user_id']) ? $_REQUEST['user_id'] : false;

        if ($scores && $user_id) {
            $userEntity = UserModel::getById($user_id);
            $actionEntity = new ActionEntity([
                'group_id'         => $userEntity->group_id,
                'user_id'          => $userEntity->id,
                'user_social_id'   => $userEntity->social_id,
                'social_id'        => time(),
                'parent_social_id' => time(),
                'scores'           => $scores,
                'activity'         => ActivityModel::NAME_ADMIN,
            ]);
            $actionEntity->save();
        }

        $this->redirect('user/list');
    }
}

views/templates/login.php
<?php
/** 
 * @var $content string 
 */
?>
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Mediastog</title>

    <link rel="stylesheet" href="/css/bootstrap.min.css">

    <link rel="stylesheet" href="/css/font-awesome.min.css">

    <link rel="stylesheet" href="/css/style.min.css">

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i,900,900i&amp;subset=cyrillic"
          rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div class="wrapper">
    <div class="content">
        <?= $content ?>
    </div> <!-- /.content -->

    <footer class="footer">
        <hr>
        <div class="container">
            <p>© Viktorator</p>
        </div>
    </footer> <!-- /.footer -->
</div> <!-- /.wrapper -->
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/js/bootstrap.min.js"></script>
<script src="/js/popper.min.js"></script>
<script src="/js/mobile-detect.js"></script>
<script src="/js/murmurHash3.min.js"></script>
</body>
</html>

views/templates/main.php
<?php
/**
 * @var $content string
 */
?>
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Mediastog</title>

    <link rel="stylesheet" href="/css/bootstrap.min.css">

    <link rel="stylesheet" href="/css/font-awesome.min.css">

    <link rel="stylesheet" href="/css/style.min.css">

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i,900,900i&amp;subset=cyrillic"
          rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div class="wrapper">

    <header class="header">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item <?= "$this->controller/$this->action" == 'site/index' ? 'active' : ''?>">
                            <a class="nav-link" href="/">Home</a>
                        </li>
                        <li class="nav-item <?= $this->controller == 'lead' ? 'active' : ''?>">
                            <a class="nav-link" href="/lead/list">Отпечатки</a>
                        </li>
                        <li class="nav-item <?= $this->controller == 'admin' ? 'active' : ''?>">
                            <a class="nav-link" href="/admin/list">Админы</a>
                        </li>
                        <li class="nav-item <?= $this->controller == 'public' ? 'active' : ''?>">
                            <a class="nav-link" href="/public/list">Группы</a>
                        </li>
                        <li class="nav-item <?= "$this->controller/$this->action" == 'site/config' ? 'active' : ''?>">
                            <a class="nav-link" href="/site/config">Настройки</a>
                        </li>
                        <li class="nav-item <?= "$this->controller/$this->action" == 'site/activity' ? 'active' : ''?>">
                            <a class="nav-link" href="/site/activity">Активности</a>
                        </li>
                        <li class="nav-item <?= "$this->controller/$this->action" == 'user/list' ? 'active' : ''?>">
                            <a class="nav-link" href="/user/list">Пользователи</a>
                        </li>
                        <li class="nav-item <?= "$this->controller/$this->action" == 'user/top' ? 'active' : ''?>">
                            <a class="nav-link" href="/user/top">Топчики</a>
                        </li>
                        <li class="nav-item <?= $this->controller == 'error' ? 'active' : ''?>">
                            <a class="nav-link" href="/error/list">Ошибки</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </header> <!-- /.header -->

    <div class="content">
        <?= $content ?>
    </div> <!-- /.content -->

    <footer class="footer">
        <hr>
        <div class="container">
            <p>© Viktorator</p>
        </div>
    </footer> <!-- /.footer -->
</div> <!-- /.wrapper -->
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/js/popper.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
</body>
</html>

views/templates/widget.php
<?php
/**
 * @var $content string
 */
?>
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Mediastog</title>

    <link rel="stylesheet" href="/css/bootstrap.min.css">

    <link rel="stylesheet" href="/css/font-awesome.min.css">

    <link rel="stylesheet" href="/css/style.min.css">

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i,900,900i&amp;subset=cyrillic"
          rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div class="wrapper">
    <div class="content bg-white">
        <?= $content ?>
    </div> <!-- /.content -->
</div> <!-- /.wrapper -->
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://vk.com/js/api/xd_connection.js?2"  type="text/javascript"></script>
<script src="/js/main.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/js/popper.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
</body>
</html>